api:
  tracemoe: https://api.trace.moe/
  anilist: https://graphql.anilist.co/

discord:
  token: ${DISCORD_TOKEN}
  emoji:
    spaghetti: U+1f35d

bot:
  prefix: !
  success: âœ“
  warning: âš 
  error: ðŸš«
  cache: 200
  status: ONLINE
  ownerId: ${DISCORD_OWNERID}

  activityStatus:
    - type: PLAYING
      text: with imouto
    - type: PLAYING
      text: LOL, pls kill me
    - type: LISTENING
      text: some good shit
    - type: LISTENING
      text: Chopin, based
    - type: WATCHING
      text: hentai
    - type: WATCHING
      text: anime
    - type: WATCHING
      text: anime (actually hentai)

  sauce:
    similarityThreshold: 0.93

logging:
  level:
    default: INFO
    com.manulaiko.shinshinjiru.discord: TRACE
